# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='load_interval',
            field=models.IntegerField(default=20),
        ),
    ]
