# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteLoader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('token', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Provider')),
            ],
            options={
                'verbose_name': 'remote loader',
                'verbose_name_plural': 'remote loaders',
            },
        ),
    ]
