# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardNotificationProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=32, null=True)),
                ('dashboard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_profile', to='core.Dashboard')),
            ],
            options={
                'verbose_name': 'dashboard notification',
                'verbose_name_plural': 'dashboard notifications',
            },
        ),
        migrations.CreateModel(
            name='KeyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True)),
                ('value', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'key-value pair',
                'verbose_name_plural': 'key-value pairs',
            },
        ),
    ]
